server:
  port: 9090
  servlet:
    context-path: /security
jwt:
  secret: 1239q6ej2137djv23evqe123dqe25sfy5634jkibrtyr
  lifetime: 30m

spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:internet-market
    username: sa
    password:
  main:
    allow-circular-references: false